Task 2
js-tasks-ru/js-20220209_matuageorge pull request #2
Opened 2022-02-15 15:39 UTC by matua

2022-02-15 15:40 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-15 22:32 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let result = arr.slice().sort((a, b) => {
проверьте, может тут `const`?

2022-02-15 22:32 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return (param === 'desc') ? result.reverse() : result;
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-02-15 22:32 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return Object.fromEntries(
good 👍

2022-02-15 22:33 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  return Object.fromEntries(
good 👍

2022-02-15 22:33 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-02-16 10:08 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-16 10:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-02-16 10:09 UTC, matua commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return (param === 'desc') ? result.reverse() : result;
Done!

2022-02-16 14:17 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>  export function sortStrings(arr, param = 'asc') {
good 👍

2022-02-16 14:17 UTC, dosandk approved these changes
good 👍

2022-02-16 14:18 UTC, merged